// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wbdhDias7fWfbBcwYSImTdVeN8I7adw',
    appId: '1:746635633854:web:fec49450796c9d5295aaef',
    messagingSenderId: '746635633854',
    projectId: 'sou-feedback-app',
    authDomain: 'sou-feedback-app.firebaseapp.com',
    storageBucket: 'sou-feedback-app.appspot.com',
    measurementId: 'G-G9B26ZVH1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyjZL-Sw8r-kyIYmLg-9a3m70aOgxqS0',
    appId: '1:746635633854:android:4d382e4308649db295aaef',
    messagingSenderId: '746635633854',
    projectId: 'sou-feedback-app',
    storageBucket: 'sou-feedback-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEo-F4rYrvucFsROOnjjtLlga3QlFzlD8',
    appId: '1:746635633854:ios:8c061fab8fd3025995aaef',
    messagingSenderId: '746635633854',
    projectId: 'sou-feedback-app',
    storageBucket: 'sou-feedback-app.appspot.com',
    iosBundleId: 'com.example.souFeedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEo-F4rYrvucFsROOnjjtLlga3QlFzlD8',
    appId: '1:746635633854:ios:db8eac43d4fd5a9495aaef',
    messagingSenderId: '746635633854',
    projectId: 'sou-feedback-app',
    storageBucket: 'sou-feedback-app.appspot.com',
    iosBundleId: 'com.example.souFeedbackApp.RunnerTests',
  );
}
